version: '3.7'
volumes:
  docker_volumes:
services:
  teamcity:
    image: jetbrains/teamcity-server
    ports:
      - "80:8111"
  buildagent:
    build: ./buildagent
    privileged: true
    environment: 
      - SERVER_URL=http://teamcity:8111
      - DOCKER_IN_DOCKER=start
    volumes:
      - "docker_volumes:/var/lib/docker" 
    depends_on: 
      - teamcity
